/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/000-a': RouteRecordInfo<
      '/000-a',
      '/000-a',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/001-b': RouteRecordInfo<
      '/001-b',
      '/001-b',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shaders/': RouteRecordInfo<
      '/shaders/',
      '/shaders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shaders/fire': RouteRecordInfo<
      '/shaders/fire',
      '/shaders/fire',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shaders/water': RouteRecordInfo<
      '/shaders/water',
      '/shaders/water',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/000-a.vue': {
      routes:
        | '/000-a'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/001-b.vue': {
      routes:
        | '/001-b'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/shaders/index.vue': {
      routes:
        | '/shaders/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/shaders/fire.vue': {
      routes:
        | '/shaders/fire'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/shaders/water.vue': {
      routes:
        | '/shaders/water'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
